version: '2'
services:
  app:
    image: alitain/share 
    volumes:
      - ../../code/alitain/:/var/www
  nginx:
    image: alitain/nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/sites:/etc/nginx/sites-available
    depends_on:
      - php5
      - php7
    volumes_from:
      - app
  php7:
    image: alitain/php7
    volumes_from:
      - app
  php5:
    image: alitain/php5
    volumes_from:
      - app
  mysql:
    image: alitain/mysql
    ports:
      - "3306:3306"
    user: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root 
