version: '2'
services:
  app:
    image: tianon/true 
    volumes:
      - ../apps/:/var/www
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/sites:/etc/nginx/sites-available
    depends_on:
      - php
    volumes_from:
      - app
  php:
    build:
      context: ./php
    volumes_from:
      - app
  mysql:
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' 
